- hosts: all
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create custom index.html
      copy:
        dest: /var/www/html/index.html
        content: "Hello from Multi-Cloud setup! Automated by Terraform and Ansible."
